name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install boost library
        run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev

      - name: Configure
        run: cmake -B build .

      - name: Build
        run: cmake --build build

      - name: Test
        run: ./build/test/web3cpp_test
